title: "Ciberseguridad práctica para profes"
description: "Hábitos y recursos para reducir riesgos en el centro. Web con prácticas cortas por apartado."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - index.md
  - practicas/index.md
  - recursos.md
show_downloads: false
